version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      python-runtime:
        patterns:
          - simpy
          - numpy
          - pandas
          - PyYAML
          - scipy
          - matplotlib
      python-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
